### PR TITLE
implement image to quiz if needed

### PR DESCRIPTION
**Pull request by Alvalens**
## Description
implement image to quiz if there a quiz url in the json file

## File Changed
 - `quiz/[slug].jsx`  add a block of code to show image in the quiz page
- `quizzes/firebase.json`  add some test image url

## Types of changes
- [x] New feature

### CODE REVIEW

**Review by vzrenggamani — CHANGES_REQUESTED** [review]
Could you please clarify when the image is not presenting in the options, what happens in the rendering?

**Comment by Alvalens** [comment]
> Could you please clarify when the image is not presenting in the options, what happens in the rendering?

the implementation of the image still only on the question, the options havent implement image yet

**Comment by vzrenggamani** [comment]
> > Could you please clarify when the image is not presenting in the options, what happens in the rendering?
> 
> the implementation of the image still only on the question, the options havent implement image yet

I see, but how about the images not present in the question?? like the images link not present? 

image

Any needs for conditional rendering when the images link not present

**Comment by Alvalens** [comment]
> > > Could you please clarify when the image is not presenting in the options, what happens in the rendering?
> > 
> > 
> > the implementation of the image still only on the question, the options havent implement image yet
> 
> I see, but how about the images not present in the question?? like the images link not present?
> 
> image
> 
> Any needs for conditional rendering when the images link not present

here are some example when link is empty and not empty at the json file
_when the link is empty_
p1

_when the link is not empty_
p2

**Pull request merged**
